name = "Pidoh"
uuid = "b088d0e4-a074-4730-af8b-77b924d8a905"
authors = ["Amirhossein Rajabi"]
version = "0.1.0"

[deps]


[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Test", "SafeTestsets"]
